name: Peekraw
options:
  bundleIdPrefix: com.alexkolov
  deploymentTarget:
    iOS: "16.0"
settings:
    DEVELOPMENT_TEAM: DLA7THG83Q
targets:
  Peekraw:
    type: application
    platform: iOS
    sources:
      - Common
      - Peekraw
    info:
      path: Peekraw/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: Fuji raw image
            LSHandlerRank: Default
            LSItemContentTypes:
              - com.fuji.raw-image
            CFBundleTypeRole: Viewer
        NSPhotoLibraryAddUsageDescription: Test
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.content
              - public.data
            UTTypeDescription: Fuji raw image
            UTTypeIdentifier: com.fuji.raw-image
            UTTypeTagSpecification:
              public.filename-extension:
                - raf
    dependencies:
      - package: Flow
      - package: LibRawKit
        product: RawKit
      - package: SnapKit
  PeekrawTests:
    type: bundle.unit-test
    platform: iOS
    sources: PeekrawTests
    dependencies:
      - target: Peekraw
  PeekrawUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: PeekrawUITests
    dependencies:
      - target: Peekraw
packages:
  Flow:
    url: https://github.com/alexito4/Flow.git
    from: 1.0.0
  LibRawKit:
    url: https://github.com/akolov/LibRawKit.git
    branch: main
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0
